### ISSUE TITLE
Figure out regionOverrides use cases, possibly how to do them with a request_func

### ISSUE THREAD

**Issue by lvh** [rackerlabs/otter#769] opened 2014-11-13 11:16 UTC
Right now, the worker code picks the region to do CLB stuff in separately from the region to do everything else in, using `regionOverrides` from the config. I've been told this is necessary (or was, at least) for staging.

Now that we've slowly started introducing some `request_func` stuff in worker, I noticed a problem; `get_request_func` just takes a fixed region. That's usually fine, but makes it impossible to use a different region just for e.g. CLB, which is exactly what the code currently does.

Maybe we don't actually need `regionOverrides` anymore. (Ping @shawnashlee or @kivattik?). If we do, no biggie: we can keep using the old `lb_region` stuff in worker, and we don't have to answer this question until convergence, because presumably we'd want to base all of that on the pure `request_func` stuff.

**Comment by radix** [comment] 2015-01-20 15:07
This may be solved by #896, but maybe get_service_configs needs updated to honor some configuration key for CLB? ping @lvh?

**Comment by radix** [comment] 2015-02-10 00:43
Still not sure about this. @lvh or @manishtomar or @cyli : given the changes recently to the way regions work in service_request, what still needs to be done here?

**Comment by cyli** [comment] 2015-02-10 00:53
@radix: the overrides are basically only necessary because they're weird on staging.  If we decide we aren't ever going to support staging unless they make it look like production, we're probably ok not supporting it?  Seems like a @wirehead question

**Comment by wirehead** [comment] 2015-02-10 04:26
No, we probably still have to support staging without requiring them to change things.

But, given it's not the expected behavior, maybe instead of a region override, we can just override the URL such that we support weird staging a different way -- providing an override URL for LB instead of a region override, for example.

**Comment by radix** [comment] 2015-02-10 06:11
So, we need to allow configuring CLB regions separate from everything else. that's fine. Yet another use-case for making our remote-service-configuration more general :)

**Comment by manishtomar** [comment] 2015-05-06 06:12
@radix Can this be closed since service_config from `otter.constants` can contain service specific configuration?

**Comment by radix** [comment] 2015-05-06 15:02
@manishtomar Yeah, I'm not sure what's actionable on this ticket. If the ticket was: "Allow overriding CLB region in config" or something, then it would be clear...

Right now our `get_service_configs` function returns the globally configured region for CLB, unconditionally. We could change it so the config file has a way to specify the CLB region specifically, and it would be easy to update the code to honor that. Do we need to do this?

**Comment by cyli** [comment] 2015-05-06 16:46
@radix - would probably check with @wirehead.  I'd suggest though, that if being able to specify a different region is already broken for convergence, then I'd recommend that we just leave it until someone tells us we have to be able to deploy on a staging environment, and staging insists on having different service names than prod.

**Comment by wirehead** [comment] 2015-05-06 18:14
I don't think this is a high priority bug.

**Comment by radix** [comment] 2015-07-30 17:35
Closing in favor of #1628.

**Closed by radix** 2015-07-30 17:35 UTC
Labels: tech-debt
