### ISSUE TITLE
policy cooldown is not honored sometimes

### ISSUE THREAD

**Issue by manishtomar** [rackerlabs/otter#942] opened 2015-01-21 20:47 UTC
https://as-jenkins.rax.io/job/otter-cloudcafe-prod-syd-quick-system-tests/260/

The `test_system_policy_down_cooldown` test in above run failed. Policy f3344e08-a28d-48cb-a2d9-fbe77d757edf was created with cooldown=3 and when executed again (almost immediately) succeeded instead of returning 403. The [logs](https://dev-otterlogs.fedsso.rackspace.com/#dashboard/temp/aktw1QQASPCLR9kuKN7vKw) for the above policy execution clearly show the time between executions was few ms.

**Comment by manishtomar** [comment] 2015-02-03 17:53
https://as-jenkins.rax.io/job/otter-cloudcafe-prod-syd-quick-system-tests/262/console too

**Comment by manishtomar** [comment] 2015-02-04 17:40
I've been struggling to debug this. This most likely reason seems to be that policy execution request taking long time (5 seconds) to return due to `view_state` taking time. This causes the next policy execution to occur after 5 seconds from otter's perspective that is > 3 seconds cool-down time. However, I am not able to confirm this from the execution times. In above [test run](https://as-jenkins.rax.io/job/otter-cloudcafe-prod-syd-quick-system-tests/262/console) the first policy exec time stored is 2015-01-23T07:29:52.205597Z and next policy exec check is happening at 2015-01-23T07:29:54.965Z base on the [logs](https://dev-otterlogs.fedsso.rackspace.com/#dashboard/temp/97MJOM2BSBKJFcOyOsyKcA). I'll try debugging it some time later to clear my mind.

**Comment by cyli** [comment] 2015-02-05 19:40
Just a hypothesis - 

These particular failures seem to be happening in SYD, and I've been noticing a bunch of `NoNodeErrors` from kazoo in SYD when acquiring locks.  They seem to have started happening around the same time:  https://dev-otterlogs.fedsso.rackspace.com/#dashboard/temp/zrXLCfntQ5iZHjfZAnOZiQ

I wonder if maybe one of our zookeeper nodes is on the fritz?

**Comment by cyli** [comment] 2015-02-05 19:59
@radix pointed out that we unpinned the dependency of dependency versions at some point, so we thought maybe there was a version difference.

`txkazoo` pins kazoo at 2.0, and otter had previously pinned kazoo at 2.0b1.  2.0b1 is still being used, so that doesn't seem to be it.  :|  And @radix confirms there are no implementation changes between 2.0b1 and 2.0.

**Comment by cyli** [comment] 2015-02-05 20:48
Nope, I just misunderstood what this issue was - I thought both policies were getting executed at the same time.  Will move the node issue to another issue in our deployment repo.

@manishtomar and I looked at the logs some more and it seems to be caused by slow DB queries - the first policy execution time was stored as 2015-01-23T07:29:52.205597Z, and the second request comes in at 2015-01-23T07:29:54.955Z.  But before a policy is executed it needs to gather the policy information, the launch config, and the group config.  Getting the group config took 3 seconds, so by the time the cooldown was evaluated to determine whether the policy could execute, it was 2015-01-23T07:29:57.991Z already, which is past the cooldown.

The slow queries seem to be that one of the cassandra nodes in Sydney is having issues with its network, so every 4th query was slow.

Closing this issue and filing new issues in our ops repo.

**Closed by cyli** 2015-02-05 20:48 UTC
Labels: bug
