### ISSUE TITLE
Refresh CloudCAFE to latest version and make it work with Jenkins

### ISSUE THREAD

**Issue by sam-falvo** [rackerlabs/otter#913] opened 2015-01-15 22:09 UTC

**Comment by sam-falvo** [comment] 2015-01-15 22:15
fyi @shawnashlee -- if you could get in touch with us (or we with you if we start this before you get around to it), that'd be awesome!  Thanks!

**Comment by radix** [comment] 2015-01-20 15:04
Is this a duplicate of #725?

**Comment by kivattik** [comment] 2015-02-10 22:39
Yes, I'm closing this since it is effectively duplication of #725.

**Closed by kivattik** 2015-02-10 22:39 UTC
Labels: EPIC, QE
